# Generated by Django 5.0.7 on 2024-11-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cages', '0004_alter_cage_animal_alter_cage_animal_food_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedanimalfood',
            old_name='food_animal_amount',
            new_name='animal_food_amount',
        ),
    ]
