# Generated by Django 5.0.7 on 2024-11-04 18:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('animal_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Nombre de animal')),
                ('observations', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('hability', models.BooleanField(verbose_name='Habilitado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.userasigned')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
            },
        ),
        migrations.CreateModel(
            name='AnimalFood',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('animal_food_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Nombre de concentrado')),
                ('observations', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('hability', models.BooleanField(verbose_name='Habilitado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.userasigned')),
            ],
            options={
                'verbose_name': 'Concentrado',
                'verbose_name_plural': 'Concentrados',
            },
        ),
    ]
