# Generated by Django 5.0.7 on 2024-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='animalfood',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
    ]
