# Generated by Django 5.0.7 on 2024-10-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicaluser_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='change_password',
            field=models.BooleanField(default=False, verbose_name='Cambiar contraseña'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='change_password_next_session',
            field=models.BooleanField(default=False, verbose_name='Cambiar contraseña en el siguiente inicio de sesion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='change_password',
            field=models.BooleanField(default=False, verbose_name='Cambiar contraseña'),
        ),
        migrations.AlterField(
            model_name='user',
            name='change_password_next_session',
            field=models.BooleanField(default=False, verbose_name='Cambiar contraseña en el siguiente inicio de sesion'),
        ),
    ]
