# Generated by Django 5.0.7 on 2024-10-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_historicaluser_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Ingreso a api'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Ingreso a api'),
        ),
    ]
