# Generated by Django 5.0.7 on 2024-11-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_historicaluser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='rol',
            field=models.CharField(choices=[('U', 'USER'), ('A', 'ADMIN')], default='U', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('U', 'USER'), ('A', 'ADMIN')], default='U', max_length=20),
        ),
    ]
