# Generated by Django 5.0.7 on 2024-11-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_change_password_historicaluser_changepassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(0, 'USER'), (1, 'ADMIN')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(0, 'USER'), (1, 'ADMIN')]),
        ),
    ]
