# Generated by Django 5.0.7 on 2024-11-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_historicaluser_rol_alter_user_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='rol',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='rol',
            new_name='role',
        ),
    ]
