# Generated by Django 5.0.7 on 2024-11-06 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre de empresa'),
        ),
    ]
