# Generated by Django 5.0.7 on 2024-11-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='usernameextension',
            new_name='usernameExtension',
        ),
    ]
