# Generated by Django 5.0.7 on 2024-11-27 18:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFoodMove',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Ingreso'), (1, 'Uso')], verbose_name='Tipo de movimiento')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de concentrado',
                'verbose_name_plural': 'Movimientos de concentrados',
            },
        ),
        migrations.CreateModel(
            name='AnimalMove',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso')),
                ('age', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Edad')),
                ('amount_animals', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de animales')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Entrada'), (1, 'Salida'), (2, 'Muerte')], verbose_name='Tipo de movimiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de animal',
                'verbose_name_plural': 'Movimientos de animales',
            },
        ),
    ]
