# Generated by Django 5.0.7 on 2024-11-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalmove',
            name='amount_animals',
            field=models.IntegerField(default=1, verbose_name='Cantidad de animales'),
        ),
    ]
