# Generated by Django 5.0.7 on 2024-11-27 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_rename_usernameextension_company_usernameextension'),
        ('reports', '0002_alter_animalmove_amount_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalmove',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.userasigned'),
        ),
    ]
