# Generated by Django 5.0.7 on 2024-11-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cages', '0005_rename_food_animal_amount_feedanimalfood_animal_food_amount'),
        ('reports', '0004_alter_animalfoodmove_type_alter_animalfoodmove_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsigAnimalFoodMove',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('animalfood_move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.animalfoodmove')),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cages.cage')),
            ],
        ),
        migrations.CreateModel(
            name='AsigAnimalMove',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('animal_move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.animalmove')),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cages.cage')),
            ],
        ),
    ]
